# Generated by Django 5.0.7 on 2025-01-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='product',
            name='degree',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
