# Generated by Django 5.0.7 on 2025-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_is_active_alter_comment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateinformation',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='product_file'),
        ),
    ]
