# Generated by Django 5.0.7 on 2025-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_privateinformation_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateinformation',
            name='product_file',
        ),
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='product_file'),
        ),
    ]
