# Generated by Django 5.0.7 on 2024-12-12 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usermodel_phonenumber_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.RegexValidator(message='Username faqat lotin harflari va raqamlardan iborat bo‘lishi kerak. Joy tashlashga ruxsat yo‘q.', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
