# Generated by Django 5.0.7 on 2024-10-18 05:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Bu telefon raqamiga ega foydalanuvchi allaqachon mavjud.'}, help_text='Majburiy. Format: +998XXXXXXXXX.', max_length=13, unique=True, validators=[app.models.UnicodePhoneValidator()], verbose_name='phone'),
        ),
    ]
