<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-12-17 10:23
=======
# Generated by Django 5.0.7 on 2024-12-17 09:57
>>>>>>> b823700b02bc4969d0abc4a4e47b06bdddb023c6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("app", "0009_alter_usermodel_username"),
=======
        ('app', '0009_alter_usermodel_username'),
>>>>>>> b823700b02bc4969d0abc4a4e47b06bdddb023c6
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="category",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
=======
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
>>>>>>> b823700b02bc4969d0abc4a4e47b06bdddb023c6
        ),
    ]
