# Generated by Django 5.0.7 on 2025-01-10 11:57

import django.utils.timezone
import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('investor', 'Investor'), ('startup', 'Startup')], max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_profile/')),
                ('username', models.CharField(error_messages={'unique': 'Bu username ga ega foydalanuvchi allaqachon mavjud.'}, help_text="Majburiy. Username faqat harflar va raqamlardan iborat bo'lishi kerak.", max_length=30, unique=True, verbose_name='username')),
                ('phone', models.CharField(error_messages={'unique': 'Bu telefon raqamiga ega foydalanuvchi allaqachon mavjud.'}, help_text='Majburiy. Format: +998XXXXXXXXX.', max_length=13, unique=True, validators=[userapp.models.UnicodePhoneValidator()], verbose_name='phone')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('approved', 'Tasdiqlangan')], default='new', max_length=100)),
                ('code', models.CharField(max_length=6, null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
