<<<<<<< HEAD
# Generated by Django 5.0.7 on 2025-01-10 05:39
=======
# Generated by Django 5.0.7 on 2025-01-04 08:23
>>>>>>> 631fdac642768c98252b74b3e27cb3b6a47a5f4f

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_usermodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='image',
            new_name='profile_image',
        ),
    ]
